### ISSUE TITLE
Sticky container for tabs from external applications

### ISSUE THREAD

**Issue by omares** [menhera-org/TabArray#6] opened 2022-01-20 10:05 UTC
When opening a new tab using an external application it would be awesome when the URL is opened in the currently active container by default. 

Having this as an option would ensure not breaking existing behaviour.

**Comment by metastable-void** [comment] 2022-01-20 17:07
I am going to implement an addon option `tab.external.containerOption` with following possible values:
value | description
------|------------
`choose` (default) | Select a container each time
`sticky` | Open in active container
`disabled` | Disabled (Open in No Container)

UI-wise, this will be presented as a dropdown menu. (`<select>`)

**Comment by omares** [comment] 2022-01-21 10:16
Hey, I just checked the latest version and unfortunately, the feature is not working for me/ Links from external applications are still opened in no container, albeit having selected "open in last active container". Cheers

**Comment by omares** [comment] 2022-01-25 08:49
@metastable-void no, no. My last active container is "Work" and still external links for me are opened in "No container"

**Comment by metastable-void** [comment] 2022-01-26 06:23
Reopened.

**Comment by metastable-void** [comment] 2022-02-10 08:39
I could not reproduce the issue in my environment. Do you use any other extensions with this addon? If so, does the issue remain when other extensions are disabled? @omares

**Comment by metastable-void** [comment] 2022-02-23 11:24
Hopefully fixed in the latest main branch. Please report any problems found.

**Comment by metastable-void** [comment] 2022-08-29 13:51
Closing. Please open a new issue if you find another problem.

**Closed by metastable-void** 2022-08-29 13:51 UTC
Labels: bug, enhancement
